//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_flawors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_flawors()
        {
            this.tbl_reciepe = new HashSet<tbl_reciepe>();
        }
    
        public int fl_id { get; set; }
        public string fl_name { get; set; }
        public string fl_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_reciepe> tbl_reciepe { get; set; }
    }
}
